"""
ReportFormatter Molbot — Specialized skill agent.

Takes raw AI analysis text and formats it into a structured,
patient-friendly JSON report. This endpoint is x402-gated,
meaning other molbots (like the Orchestrator) must pay to use it.

This demonstrates the "specialized skill molbot that charges for
its services using x402" concept from the hackathon bounty.
"""

import logging
import re

logger = logging.getLogger(__name__)


def format_analysis(raw_text: str) -> dict:
    """
    Parse raw AI analysis text into a structured report.

    Extracts sections like Summary, Key Findings, Risk Level,
    Recommendations, and Disclaimer from the AI's markdown output.
    """
    if not raw_text or len(raw_text.strip()) < 10:
        return {
            "formatted": True,
            "sections": [],
            "error": "Input text too short to format",
        }

    sections = []

    # Extract Summary
    summary = _extract_section(raw_text, r"\*\*Summary\*\*", r"\*\*")
    if summary:
        sections.append({"title": "Summary", "content": summary.strip(), "icon": "📋"})

    # Extract Key Findings
    findings = _extract_section(raw_text, r"\*\*Key Findings\*\*", r"\*\*")
    if findings:
        bullet_points = [
            line.strip().lstrip("- •*").strip()
            for line in findings.split("\n")
            if line.strip() and line.strip() not in ("", "-")
        ]
        sections.append({
            "title": "Key Findings",
            "content": bullet_points if bullet_points else findings.strip(),
            "icon": "🔍",
        })

    # Extract Risk Level
    risk_match = re.search(
        r"\*\*Risk Level\*\*[:\s]*(Low|Moderate|High|Critical)",
        raw_text,
        re.IGNORECASE,
    )
    if risk_match:
        risk_level = risk_match.group(1).title()
        risk_colors = {
            "Low": "#22c55e",
            "Moderate": "#eab308",
            "High": "#f97316",
            "Critical": "#ef4444",
        }
        sections.append({
            "title": "Risk Level",
            "content": risk_level,
            "color": risk_colors.get(risk_level, "#6b7280"),
            "icon": "⚠️",
        })

    # Extract Detected Concerns (for symptom analysis)
    concerns = _extract_section(raw_text, r"\*\*Detected Concerns\*\*", r"\*\*")
    if concerns:
        sections.append({
            "title": "Detected Concerns",
            "content": concerns.strip(),
            "icon": "🩺",
        })

    # Extract Possible Conditions
    conditions = _extract_section(raw_text, r"\*\*Possible Conditions\*\*", r"\*\*")
    if conditions:
        items = [
            line.strip().lstrip("- 0123456789.•*").strip()
            for line in conditions.split("\n")
            if line.strip() and len(line.strip()) > 3
        ]
        sections.append({
            "title": "Possible Conditions",
            "content": items if items else conditions.strip(),
            "icon": "🧬",
        })

    # Extract Recommendations / Immediate Actions
    recs = _extract_section(raw_text, r"\*\*(Recommendations|Immediate Actions)\*\*", r"\*\*")
    if recs:
        items = [
            line.strip().lstrip("- 0123456789.•*").strip()
            for line in recs.split("\n")
            if line.strip() and len(line.strip()) > 3
        ]
        sections.append({
            "title": "Recommendations",
            "content": items if items else recs.strip(),
            "icon": "💡",
        })

    # Extract Questions for Doctor
    questions = _extract_section(raw_text, r"\*\*Questions for Your Doctor\*\*", r"\*\*")
    if questions:
        items = [
            line.strip().lstrip("- 0123456789.•*").strip()
            for line in questions.split("\n")
            if line.strip() and len(line.strip()) > 3
        ]
        sections.append({
            "title": "Questions for Your Doctor",
            "content": items if items else questions.strip(),
            "icon": "❓",
        })

    # Disclaimer
    sections.append({
        "title": "Disclaimer",
        "content": (
            "This analysis was generated by AI and is NOT a substitute for "
            "professional medical advice, diagnosis, or treatment. Always seek "
            "the advice of your physician or other qualified health provider."
        ),
        "icon": "⚕️",
    })

    # If no sections were parsed, return the raw text as a single section
    if len(sections) <= 1:
        sections.insert(0, {
            "title": "Analysis",
            "content": raw_text.strip(),
            "icon": "📄",
        })

    return {
        "formatted": True,
        "sections": sections,
        "sectionCount": len(sections),
        "formattedBy": "ReportFormatter Molbot",
    }


def _extract_section(text: str, header_pattern: str, next_header: str) -> str:
    """Extract text between a markdown header pattern and the next header."""
    match = re.search(header_pattern, text, re.IGNORECASE)
    if not match:
        return ""

    start = match.end()
    # Find the next bold header after this one
    remaining = text[start:]
    next_match = re.search(r"\n\s*\d*\.?\s*\*\*[A-Z]", remaining)
    if next_match:
        return remaining[: next_match.start()]
    return remaining
